# name of the serverless service
service: portfolio

configValidationMode: error

provider:
  name: aws
  runtime: python3.8 
  stage: test
  region: eu-central-1

functions:
  ping:
    name: getReandomNumber
    handler: src/ping.handle

  randomNumber:
    name: random-number
    handler: src/randomNumber.get
   

# https://www.serverless.com/framework/docs/providers/aws/guide/packaging/
#package:
#  patterns:
#    - "!**"
#    - "src/**"

package:
  individually: true
  exclude: 
    - ./**
  include:
    - src/**